apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 759320821027.dkr.ecr.ap-northeast-2.amazonaws.com/jymin-frontend
  newName: 759320821027.dkr.ecr.ap-northeast-2.amazonaws.com/jymin-frontend
  newTag: abcdefg
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
